### ISSUE TITLE
Package given as bad example of small module

### ISSUE THREAD

**Issue by dandv** [tjmehta/is-positive-integer#16]
https://medium.com/@alper/how-about-this-one-that-depends-on-3-packages-and-is-one-trivial-line-https-github-com-tjmehta-2e226b22fa5

**Comment by tjmehta** [comment]
The code the article references has been updated. This package is no-longer one line. As you can see in the package.json, this module no longer has any dependencies. Also note, the logic is not trivial it has been extended to deal with safe-integers in Javascript. 

Finally, everything you read on the internet is not truth; everyone is entitled to their own opinions. This package's ability to evolve was enabled by a 1-liner package being published to npm. Myself and many others in the Node community like the idea micro-packages.. ( see https://github.com/sindresorhus/)

**Comment by Rudxain** [comment]
I found another one: https://www.davidhaney.io/npm-left-pad-have-we-forgotten-how-to-program

It's used as one of many examples, and it has been updated to reflect the 0 dependencies that the package has now

**Comment by tjmehta** [comment]
This package has 46 weekly downloads on npm - https://www.npmjs.com/package/is-positive-integer
